In [2]:
import torch as t

In [3]:
x = t.tensor(4.0, requires_grad=True)

In [4]:
x

tensor(4., requires_grad=True)

In [5]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
##back propogration y = 2*x
y.backward()

In [7]:
y

tensor(16., grad_fn=<PowBackward0>)

In [8]:
print(x.grad)

tensor(8.)


In [9]:
print(y.grad)

None


C:\Users\Mehta\AppData\Local\Temp\ipykernel_4068\1324337507.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print(y.grad)


In [10]:
lst = [[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]]
torch_input = t.tensor(lst, requires_grad=True) 

In [11]:
torch_input

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)

In [12]:
y = torch_input**3 + torch_input**2

In [13]:
y

tensor([[  2.,  12.,  36.],
        [ 80., 150., 252.],
        [392., 576., 810.]], grad_fn=<AddBackward0>)

In [14]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [15]:
z = y.sum()
z

tensor(2310., grad_fn=<SumBackward0>)

In [16]:
z.backward()

In [17]:
z

tensor(2310., grad_fn=<SumBackward0>)

In [18]:
print(torch_input.grad)

tensor([[  5.,  16.,  33.],
        [ 56.,  85., 120.],
        [161., 208., 261.]])


In [22]:
print(torch.nn.Linear(3,2))
print(torch.nn.ReLU())


Linear(in_features=3, out_features=2, bias=True)


AttributeError: module 'torch.nn' has no attribute 'densed_linear'