In [1]:
import torch 


In [2]:
torch.__version__

'2.4.0+cu124'

In [3]:
import numpy as np
lst = [3,4,5,6,]
arr = np.array(lst)

In [4]:
arr

array([3, 4, 5, 6])

In [5]:
arr.dtype

dtype('int32')

In [6]:
tensors=torch.from_numpy(arr)

In [7]:
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [8]:
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [9]:
tensors[3] = 100

In [10]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [11]:
tensor_arr=torch.tensor(arr)

In [13]:
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [14]:
tensor_arr.dtype

torch.int32

In [15]:
tensor_arr[3] = 120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120], dtype=torch.int32)
[  3   4   5 100]


In [17]:
torch.zeros(2,3, dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [21]:
torch.device('cuda')

device(type='cuda')

In [27]:
torch.cuda.get_device_name()

'NVIDIA GeForce GTX 1650 Ti'

In [28]:
torch.ones(2,3, dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [29]:
a = torch.tensor([3,4,5,6], dtype = torch.float64)
b = torch.tensor([3,4,5,6], dtype = torch.float64)

In [30]:
print(a+b)

tensor([ 6.,  8., 10., 12.], dtype=torch.float64)


In [31]:
c = torch.zeros(3)
torch.add(a,b, out = c)

C:\Users\Mehta\AppData\Local\Temp\ipykernel_22340\2886153046.py:2: UserWarning: An output with one or more elements was resized since it had shape [3], which does not match the required output shape [4]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:35.)
  torch.add(a,b, out = c)


tensor([ 6.,  8., 10., 12.])

In [32]:
torch.add(a,b).sum()

tensor(36., dtype=torch.float64)

Dot Products


In [33]:
import torch as t

In [34]:
x = t.tensor([3,4,5,6], dtype = t.float64)
y = t.tensor([3,4,5,6], dtype = t.float64)
x.mul(y)

tensor([ 9., 16., 25., 36.], dtype=torch.float64)

In [35]:
x.dot(y)

tensor(86., dtype=torch.float64)

In [36]:
x = t.tensor([[1,4,2], [1,5,5]], dtype = t.float64)
y = t.tensor([[5,7], [8,6],[9,11]],dtype = t.float64)
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

In [37]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)

In [38]:
x@y

tensor([[55., 53.],
        [90., 92.]], dtype=torch.float64)